### ISSUE TITLE
oduleNotFoundError: No module named 'goat'

### ISSUE THREAD

**Issue by 74284853** [Ram81/goat-bench#11]
When I run ,SenseAct-NN Monolithic Baseline'Evaluation ,I get the following error.I have configured the environment according to the instructions and executed 'pip install -e .'
![image](https://github.com/Ram81/goat-bench/assets/75053635/5a6ec5be-49cc-4969-b3aa-de45701978a9)

**Comment by yusirhhh** [comment]
I have the same issue when I run the evaluation script.  @Ram81 @74284853

**Comment by Ram81** [comment]
Hi @74284853  @yusirhhh, I have fixed the issue with the checkpoint loading. Can you please pull the latest checkpoint from HF and try evaluating again?

Let me know if you face any issues

**Comment by Ram81** [comment]
Closing this issue as the pointed error is fixed and the thread has been inactive for few weeks
