### ISSUE TITLE
Could you please provide a more detailed instruction on the download and preparation of hm3d dataset?

### ISSUE THREAD

**Issue by CZtheHusky** [Ram81/goat-bench#15]
Thank you for your work!

I tried to download with the following command from [here](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#habitat-matterport-3d-research-dataset-hm3d), but it did not work.

`python -m habitat_sim.utils.datasets_download --username <api-token-id> --password <api-token-secret> --uids hm3d_minival_v0.2`

I believe the repo of the dataset should be [here](https://github.com/matterport/habitat-matterport-3dresearch), and I have downloaded `hm3d-minival-habitat-v0.2.tar`, `hm3d-minival-semantic-configs-v0.2.tar`, `hm3d-train-habitat-v0.2.tar`, `hm3d-val-habitat-v0.2.tar`. Neither of these has the structure like this:
  ```bash
  ├── goat-bench/
  │  ├── data
  │  │  ├── scene_datasets/
  │  │  │  ├── hm3d/
  │  │  │  │  ├── JeFG25nYj2p.glb
  │  │  │  │  └── JeFG25nYj2p.navmesh
  ```

**Comment by Ram81** [comment]
Hi @CZtheHusky , the dataset you downloaded is correct and the structure available in default dataset is correct. You can read more about downloading dataset [here](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#habitat-matterport-3d-research-dataset-hm3d). The README had a incorrect dataset structure listed. I have fixed the README to be consistent with actual dataset. Thanks for pointing out the issue.
