### ISSUE TITLE
Hi, what is the "full HM3D"?

### ISSUE THREAD

**Issue by Yonggie** [Ram81/goat-bench#16]
![图片](https://github.com/Ram81/goat-bench/assets/31330044/87e12f5f-8295-48e5-bbe3-31aec968006c)

and the [link](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#habitat-matterport-3d-research-dataset-hm3d) contains several datasets.
Is the largest dataset the "full dataset" mentioned?
![图片](https://github.com/Ram81/goat-bench/assets/31330044/9f346220-e1a9-4095-932e-81052ad532b7)

**Comment by Ram81** [comment]
Hi @Yonggie by full HM3D dataset we mean you need both the training and validation scenes. That would mean running following commands

```
python -m habitat_sim.utils.datasets_download --username <api-token-id> --password <api-token-secret> --uids hm3d_train_habitat_v0.2

python -m habitat_sim.utils.datasets_download --username <api-token-id> --password <api-token-secret> --uids hm3d_val_habitat_v0.2
```

Let me know if you face any issues

**Comment by Yonggie** [comment]
Yes, thx!

**Comment by Yonggie** [comment]
Hi, I mannually downloaded the ``hm3d-train-habitat-v0.2.tar`` and ``hm3d-val-habitat-v0.2.tar``, and neither of them have the ``nav mesh`` file mentioned in the readme. Is it different if I use the scripts u mentioned to download them?

![图片](https://github.com/user-attachments/assets/c63b486c-5c91-488b-9351-bd35d634fca4)
![图片](https://github.com/user-attachments/assets/190c5825-6dbf-407e-a4cd-33b5a2dec0e3)


BTW, are the ``nav mesh`` files used for metrics?

**Comment by Ram81** [comment]
Hi @Yonggie, if you run training/evaluation we recompute the navmesh on the fly so it shouldn't be a problem if navmesh files don't exists. Let me know if there are any errors.
