### ISSUE TITLE
AttributeError: 'BaseEpisode' object has no attribute 'tasks'

### ISSUE THREAD

**Issue by dzh19990407** [Ram81/goat-bench#17]
Thanks for your appealing work on the multi-modal lifelong navigation project. I encountered an issue when trying to run the provided scripts.

The error I'm seeing is:
```
AttributeError: 'BaseEpisode' object has no attribute 'tasks
```
This error occurs in the following code:
https://github.com/Ram81/goat-bench/blob/74c41d19d4a4c3608d1575b512087b5a529aee0e/goat_bench/trainers/ppo_trainer_no_2d.py#L353-L355

I found that the current_episodes_info variable is a list of BaseEpisode objects, whose source code is here:
https://github.com/facebookresearch/habitat-lab/blob/2c7519b1baead8d5bc9557dd53d2a01e4aa9c6e5/habitat-lab/habitat/core/dataset.py#L43-L53

It seems the `BaseEpisode` class does not have an attribute named `tasks`, which is causing the error.

I was able to work around this by commenting out the lines of code that were trying to access the `tasks` attribute. However, this is not an ideal solution, as it may indicate a deeper issue with the code.

Could you please take a look and provide some guidance on how to resolve this error? I'm happy to provide any additional information that might be helpful.

Thank you for your time and great work on this project!

**Comment by Ram81** [comment]
@dzh19990407 Thanks for flagging this issue. The `BaseEpisode` is only supposed to contain relevant metadata to pass to evaluator to avoid sending large jsons over connections in vector environments. You can safely comment out that line and use the evaluator as we were using the `tasks` metadata for specific analysis added in the paper. I will push changes to the repo to remove this line.

**Comment by NormanMises** [comment]
emm..... The author seems to have forgotten to comment on the relevant code

**Comment by shi0rik0** [comment]
@Ram81 It seems like the bug fix hasn't been pushed yet... Could you fix this problem?
