### ISSUE TITLE
Hi, Ques about goat-bench dataset

### ISSUE THREAD

**Issue by Yonggie** [Ram81/goat-bench#18]
Every file in goat-bench has 2 keys ``goals`` and ``episodes``

I have question about the ``goals`` key information:
![图片](https://github.com/user-attachments/assets/19bb5d08-80da-4133-a7d0-6644e3afc2f6)

Is the position at NO.1 the goal ground truth?
The goal have multiple ``position`` in key ``image goal`` (at NO.2 area), is this the multiple viewpoints you mentioned in the paper?
![图片](https://github.com/user-attachments/assets/9bc22a59-71a5-4d46-b036-f95690a2f74c)

**Comment by Yonggie** [comment]
hi, is the postion in the json file the ``x,y,z`` coordinates?

**Comment by Ram81** [comment]
Hi @Yonggie, yes the poses are in `x, y, z`. You can read more about coordinate frames used in habitat [here](https://aihabitat.org/docs/habitat-sim/coordinate-frame-tutorial.html). We use the standard coordinate frame from habitat.

**Comment by Ram81** [comment]
>Is the position at NO.1 the goal ground truth?
The goal have multiple position in key image goal (at NO.2 area), is this the multiple viewpoints you mentioned in the paper?

@Yonggie yes, the first goal is the centroid of the object and it's rotation. The list of `image_goals` are various viewpoints as shown in the figure.

**Comment by Ram81** [comment]
Closing the issue due to inactivity
