### ISSUE TITLE
```val_seen_bert_embedding.pkl``` seems to not be present in HF URL

### ISSUE THREAD

**Issue by francescotaioli** [Ram81/goat-bench#20]
Hi, I'm not able to find the ```val_seen_bert_embedding.pkl``` files from```https://huggingface.co/datasets/axel81/goat-bench```.

This will cause the following exception: ```No such file or directory: 'data/goat-assets/goal_cache/language_nav/val_seen_bert_embedding.pkl```

This is related to this closed issue: https://github.com/Ram81/goat-bench/issues/5#issuecomment-2162951807

Can someone find the Bert cache files? 

Thanks in advance.

**Comment by francescotaioli** [comment]
@DragonYang-code no, I didn't solve the issue. Let's wait for the author's response,

**Comment by ytx0323** [comment]
I'm facing the same question too. @Ram81

**Comment by ytx0323** [comment]
I guess maybe the author mistake the name between scripts and the real files. I change the name and I can run it. However I encounter the question about the class PointNavResnetCLIPPolicy. I don't know how to solve it now.

**Comment by francescotaioli** [comment]
In the paper, the following is written: "**LanguageNav Policy**. For LANGUAGENAV, we encode the language goal to a target embedding gt (768-d vector) using frozen BERT base uncased [60] sentence encoder. "

Thus, @ytx0323 , I doubt the files are Bert embeddings, since the dimensions do not match

**Comment by Ram81** [comment]
@francescotaioli @ytx0323 I just uploaded the val split BERT embeddings to the HF repo. Let me know if that resolves the issue. 

@francescotaioli the embeddings used for langauge nav skill chain baseline are indeed the BERT embeddings. The old uploaded embeddings are from CLIP model.

**Comment by francescotaioli** [comment]
Thanks, @Ram81.
