### ISSUE TITLE
Raw Images for Visual Navigation

### ISSUE THREAD

**Issue by hanyangclarence** [Ram81/goat-bench#21]
Thank you for your great work!

In visual navigation task, we take images as the navigation target. I see that the features of the images in the dataset are provided, but I'm planning to adapt the dataset on another relevant task. So I'd like to know whether you can provide the raw images used in the image goals in the dataset.

Thank you!

**Comment by Ram81** [comment]
@hanyangclarence you can add a sensor similar to [this](https://github.com/Ram81/goat-bench/blob/main/goat_bench/task/sensors.py#L102) which renders the image observation instead of using cached embedding.

**Comment by hanyangclarence** [comment]
Okay, thank you! I've figured out how to do that.

**Comment by NormanMises** [comment]
> Okay, thank you! I've figured out how to do that.

您好，我看到您在 3D-Mem 中的工作提取目标照片时是使用的 场景数据集中的 view_points 列表中的机器人位置信息

![Image](https://github.com/user-attachments/assets/9d363401-9012-40d9-bfb3-6ec48715597e)

但是我也注意到 还有一个 image_goals 列表，也是位置信息，且 GOAT 代码中提取图像目标的 embedding 似乎也是用的 image_goals 中的位置信息

![Image](https://github.com/user-attachments/assets/4d169d29-88e7-423b-ac81-82e0636e7458)

![Image](https://github.com/user-attachments/assets/1f286653-5475-430a-8641-2d4b7c830317)

所以我想问一下您到底该用哪里的位置信息来提取目标照片呀？

**Comment by hanyangclarence** [comment]
我记得提取visual navigation的image goal时，用的就是image_goals的位置吧？view_points是用来确定agent是否到达target position的

**Comment by NormanMises** [comment]
> 我记得提取visual navigation的image goal时，用的就是image_goals的位置吧？view_points是用来确定agent是否到达target position的

不是啊

![Image](https://github.com/user-attachments/assets/9ad1d7c6-ab6f-41b1-b7cd-82ab6a278208)
您的代码中提取image_goals是用的["view_points"][0]["agent_state"]

**Comment by NormanMises** [comment]
> 确实哈。我确认了一下，goatbench用的是image goal, 但我现在是取的第一个viewpoint。我之后会改一下，不过应该不会对结果有很大影响。我记得这两个看起来是差不多的

好的 谢谢您😊
还有个问题，image_goals中除了position和rotation这两个位姿配置，还有hfov和image_dimensions这两个参数，如果做GOAT任务，提取图像的话，要不要也严格遵循hfov和image_dimensions呀？😕

![Image](https://github.com/user-attachments/assets/22700887-bd35-4e2f-bfc4-a1ee5e79c714)

**Comment by NormanMises** [comment]
> 那感觉应该都用的是image_goal里的坐标。我看至少提取feature确实是用的image _goal而非view_point.

对，sensor 里提取 cache 的时候用的是 image_goals，但是也有用view_points的sensor

![Image](https://github.com/user-attachments/assets/b53f010a-9646-4206-ab0a-6efd5d4eabd8)

就很迷😂

> 获取observation的时候额外加个参数

好像没这么简单，get_observations_at 这个函数只能传position和rotation两个参数，它直接用配置文件里的rgb sensor获取的图像，

![Image](https://github.com/user-attachments/assets/269cb64b-c1c4-4aae-b9e5-7fcac903f920)

我是新创了一个sim实例然后按image_goals里的配置设置sensor去获取的，但是agent参数可能设的不对，效果一般

**Comment by NormanMises** [comment]
> 我自己用这个sim的时候的api跟goatbench里的还有点不一样，是可以设置fov，视角之类的。像是[这里](https://github.com/UMass-Embodied-AGI/3D-Mem/blob/7b7ded0bed7beee33bebc7ea19583446b335f694/src/scene_goatbench.py#L106)

嗯嗯对 您的代码里直接用的 Habitat-Sim 没用 Habitat-Lab ，代码结构简单好多，Habitat-Lab 这个配置文件系统真复杂🥲

找到了 goat 提取图像传感器
![Image](https://github.com/user-attachments/assets/dbdee853-17c1-46ee-acab-2b4d6efbf090)
