### ISSUE TITLE
Unable to run Monolithic evaluation

### ISSUE THREAD

**Issue by Haochen-Niu** [Ram81/goat-bench#28]
Thank you for your great work!
I'm unable to run the evaluation of the 'SenseAct-NN Monolithic Baseline'.
```
File "~/goat-bench/goat_bench/trainers/ppo_trainer_no_2d.py", line 354, in _eval_checkpoint
    i
AttributeError: 'BaseEpisode' object has no attribute 'tasks'
```
the return result of function 'self.envs.current_episodes()' only includes 'episode_id' and 'scene_id'
![image](https://github.com/user-attachments/assets/f1a6cc30-f01b-4736-bdde-f910d075f6b6)

Can you give me some instructions, please? Thanks in advance.

**Comment by pangpangxiong520** [comment]
Hello, I'd like to ask that how you solve this AttributeError?:(
