### ISSUE TITLE
How to run the evaluation?

### ISSUE THREAD

**Issue by TSUNAMIII-7** [Ram81/goat-bench#4]
Hi! 
Thanks for your fantastic work.
I just want to run the evaluation part to see how the benchmark work for GOAT task. Is it possible to offer the checkpoint, and the caches which have been mentioned at the config documents (object_cache, image_cache, language_cache)?

**Comment by Ram81** [comment]
Hi @TSUNAMIII-7, we have updated the instructions for evaluation [here](https://github.com/Ram81/goat-bench?tab=readme-ov-file#-evaluation). In addition, the cached embeddings and checkpoints are released [here](https://github.com/Ram81/goat-bench?tab=readme-ov-file#cached-embeddings-and-model-checkpoints) .

**Comment by TSUNAMIII-7** [comment]
Thanks for your reply. It really helps!
