### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by Cassie-Lim** [Ram81/goat-bench#6]
Hi, thanks for the great work. Could you please provide the pretrained policy weights?

**Comment by Ram81** [comment]
Hi @Cassie-Lim, we have released the checkpoints for the monolithic baseline and instructions to train models with exact commands in our [README](https://github.com/Ram81/goat-bench?tab=readme-ov-file#bar_chart-training). You can find the checkpoints for [SenseAct-NN monolithic baseline here](https://github.com/Ram81/goat-bench?tab=readme-ov-file#cached-embeddings-and-model-checkpoints). As for skill chain baseline we are rerunning them and will release the checkpoints soon.

**Comment by 74284853** [comment]
> Hi @Cassie-Lim, we have released the checkpoints for the monolithic baseline and instructions to train models with exact commands in our [README](https://github.com/Ram81/goat-bench?tab=readme-ov-file#bar_chart-training). You can find the checkpoints for [SenseAct-NN monolithic baseline here](https://github.com/Ram81/goat-bench?tab=readme-ov-file#cached-embeddings-and-model-checkpoints). As for skill chain baseline we are rerunning them and will release the checkpoints soon.

Could you please provide the training and evaluation methods of Modular GOAT? This is what I am more interested in.

**Comment by Cassie-Lim** [comment]
> Hi @Cassie-Lim, we have released the checkpoints for the monolithic baseline and instructions to train models with exact commands in our [README](https://github.com/Ram81/goat-bench?tab=readme-ov-file#bar_chart-training). You can find the checkpoints for [SenseAct-NN monolithic baseline here](https://github.com/Ram81/goat-bench?tab=readme-ov-file#cached-embeddings-and-model-checkpoints). As for skill chain baseline we are rerunning them and will release the checkpoints soon.

Thanks for the reply! :D

**Comment by Ram81** [comment]
@74284853 the codebase for modular GOAT baseline is part of the home robot codebase in [this branch](https://github.com/facebookresearch/home-robot/commits/goat-sim/). However this branch is not actively maintained. We are planning to clean the codebase and release but that might take some more time.
