### ISSUE TITLE
About Table 5 in the Appendix.

### ISSUE THREAD

**Issue by kellyiss** [Ram81/goat-bench#7]
Hi, thanks for the wonderful work!

I have a question about the Performance of individual skills used for RL Skill Chain baseline which is shown in Table5 in the Appendix.
Is VAL UNSEEN EASY referring to Val Seen Synonyms Split or a subset of the Val Unseen Split?

Looking forward to your reply!

**Comment by Ram81** [comment]
Hi @kellyiss , sorry for confusion. The val unseen easy refers to val seen synonym split. Thanks for pointing this out, we will fix it on arxiv!
